[project]
name = "info698-capstone"
version = "0.1.0"
description = "Agent Based RAG system over PMC"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.20",
    "langchain-community>=0.3.19",
    "langchain-openai>=0.3.8",
    "openai>=1.66.3",
    "python-dotenv>=1.0.1",
    "streamlit>=1.42.2",
    "watchdog>=6.0.0",
]
